#!/bin/bash

pgrep -x sxhkd > /dev/null || sxhkd &

# Workspaces
bspc monitor eDP-1 -d 1 2 3 4
bspc monitor DP-3 -d 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          20
bspc config top_padding         18
bspc config left_padding        0
bspc config right_padding        0
bspc config bottom_padding        5

bspc config normal_border_color \#AD0000
bspc config active_border_color \#00FF44
bspc config focused_border_color \#00FF44
bspc config presel_feedback_color \#888888

bspc config split_ratio          0.61803398874989484820
bspc config borderless_monocle   true
bspc config gapless_monocle      true

${HOME}/.fehbg &
${HOME}/.config/polybar/forest/launch.sh &
picom --experimental-backends -b

